FROM postgres:latest
# Create sudo user
# USER root
# Create a group and user
# RUN apk update && apk add unzip && apk add whoiam
RUN whoiam
# USER kong
# WORKDIR /home/kong
# Install unzip
# USER root
# COPY get_data.sh /docker-entrypoint-initdb.d/get_data.sh
# COPY initdb.sql /docker-entrypoint-initdb.d/initdb.sql